language: ruby
rvm:
  2.1.2
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
before_script:
  - psql -c 'create database money_test' -U postgres
