language: ruby
rvm:
  2.2.4
env:
  - DB=postgresql
script:
  - "RAILS_ENV=test bundle exec rake db:setup --trace"
  - "bundle exec rspec spec"
  - "bundle exec cucumber"
  - "bundle exec rake spec:javascript"
before_script:
  - "psql -c 'create database money_test' -U postgres"
