language: ruby
rvm:
  2.1.2
env:
  - DB=postgresql
branches:
  only:
    -master
script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - bundle exec rspec spec
  - bundle exec cucumber
before_script:
  - psql -c 'create database money_test' -U postgres
